[package]
name = "webgl-wasm"
version = "0.1.0"
authors = ["YashYash <yash.saxena1217@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/main.rs"

[dependencies]
wasm-bindgen = "0.2.71"
